#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-tkr-conversion-webhook-package-sa
  namespace: #@ data.values.frameworkPackage.namespaceForPackageInstallation
  annotations:
    kapp.k14s.io/change-group: "tkr-conversion-webhook-packageinstall/serviceaccount-0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-tkr-conversion-webhook-package-cluster-role
  annotations:
    kapp.k14s.io/change-group: "tkr-conversion-webhook-packageinstall/serviceaccount-0"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
      - list
      - delete
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
    - run.tanzu.vmware.com
    resources:
    - tanzukubernetesreleases
    - osimages
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - run.tanzu.vmware.com
    resources:
    - tanzukubernetesreleases/status
    - osimages/status
    verbs:
    - get
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-tkr-conversion-webhook-package-cluster-rolebinding
  annotations:
    kapp.k14s.io/change-group: "tkr-conversion-webhook-packageinstall/serviceaccount"
    kapp.k14s.io/change-rule.0: "upsert after upserting tkr-conversion-webhook-packageinstall/serviceaccount-0"
    kapp.k14s.io/change-rule.1: "delete before deleting tkr-conversion-webhook-packageinstall/serviceaccount-0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-tkr-conversion-webhook-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-tkr-conversion-webhook-package-sa
    namespace: #@ data.values.tkrConversionWebhookPackage.namespaceForPackageInstallation
