#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-tkr-conversion-webhook-package-sa
  namespace: #@ data.values.frameworkPackage.namespaceForPackageInstallation
  annotations:
    kapp.k14s.io/change-group: "tkr-conversion-webhook-packageinstall/serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-tkr-conversion-webhook-package-cluster-role
  annotations:
    kapp.k14s.io/change-group: "tkr-conversion-webhook-packageinstall/serviceaccount"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificates
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - tkr-conversion-webhook
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - tkr-conversion-webhook/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - features
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.tanzu.vmware.com
    resources:
      - features/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-tkr-conversion-webhook-package-cluster-rolebinding
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting tkr-conversion-webhook-packageinstall/serviceaccount"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-tkr-conversion-webhook-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-tkr-conversion-webhook-package-sa
    namespace: #@ data.values.frameworkPackage.namespaceForPackageInstallation
